### ISSUE TITLE
Scrolling not working in iOS 13

### ISSUE THREAD

**Issue by mobitar** [standardnotes/secure-spreadsheets#22]
Waiting on upstream fix: https://github.com/telerik/kendo-ui-core/issues/5303

**Comment by jamesgecko** [comment]
Looks like this should be fixed in KendoUI `2020.3.915` onward.

**Comment by JaspalSuri** [comment]
Hi @jamesgecko, 

Sorry for not replying to your earlier. I was too excited to respond, apparently. @johnny243 has updated the Secure Spreadsheets editor extension to include the fix. The updated version is currently pending review and I'll comment on this thread again once it's released.

**Comment by jamesgecko** [comment]
Thanks so much! 🎉

**Comment by JaspalSuri** [comment]
The updated editor (v1.3.5) has been [released](https://github.com/standardnotes/secure-spreadsheets/releases/tag/1.3.5) (thanks to @johnny243 and @mobitar)!

**Comment by JaspalSuri** [comment]
Hi @jamesgecko,

@johnny243 will be releasing the update soon and the updated version will also include a fix for the inability to rename individual sheets via the tabs at the bottom of the Secure Spreadsheets Editor. 😃 

To rename a sheet, simply double tap its name thats contained in one of the tabs below. To dismiss the keyboard, tap on any part outside of the sheet. You can also zoom in and out of the sheet as well. 😃

(In the video below, I show how it appears when you press and hold the names contained in the tabs.)

https://user-images.githubusercontent.com/44656000/103907303-f682c500-50b5-11eb-816b-a256a12e59ce.mov
