### ISSUE TITLE
Allow worksheets to have custom names

### ISSUE THREAD

**Issue by archerships** [standardnotes/secure-spreadsheets#40]
Right now, if you add  a new worksheet to a secure spreadsheet, it has the name "Sheet1", "Sheet2", etc.   There does not appear to be a way to give each worksheet a custom name.  It would be nice if the each sheet could have it's own custom name.

**Comment by bryvin** [comment]
You can do this now actually by double clicking on the Sheet's name at the bottom, it will change into a text input field.

**Comment by archerships** [comment]
Many thanks!  I thought I had tried that, but I guess I didn't.
